name: Daily Offer Scraper

on:  
  schedule:    
    - cron: '20 18 * * *'

jobs:  
  run-scraper:    
    runs-on: ubuntu-latest    
    permissions:      
      contents: write    
    steps:    
      - name: Checkout repository code      
        uses: actions/checkout@v6    

      - name: Set up Python Environment      
        uses: actions/setup-python@v6  
        with:        
          python-version: '3.10'    

      - name: Install Libraries      
        run: |        
          python -m pip install --upgrade pip        
          pip install -r requirement.txt    

      - name: Run Perfume Scraper Script      
        run: python scraper.py    

      - name: Commit and Save the Excel Report back to GitHub      
        run: |        
          git config --global user.name "GitHub Action Scraper"        
          git config --global user.email "actions@github.com"        
          git add daily_offers.xlsx        
          git commit -m "Automated Report Update: $(date +'%Y-%m-%d')" || exit 0        
          git push origin HEAD:${{ github.ref_name }}